<?php
/**
 *
 * 文件说明: 文章管理
 *
 * Created by PhpStorm.
 * User: qs9515
 * Date: 2019/8/18
 * Time: 17:57
 *
 * $Id$
 * $LastChangedDate$
 * $LastChangedRevision$
 * $LastChangedBy$
 */
namespace application\admin\controller;
use application\admin\controller\baseController;
use application\admin\models\baseModel;
use application\admin\validate\articleValidate;
use Overtrue\Pinyin\Pinyin;

class articleController extends baseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 方法名称:sortListAction
     * 说明: 分类列表
     * @throws \SmartyException
     */
    public function sortListAction()
    {
        $search=array();
        $search['keyword']=$this->_request->getParam('keyword');
        $data=parent::_list("ben_sort",BASE_PATH.'admin/article/sortList/page/(:num)/',$search,"updated desc",array('sort_name','sort_info'));
        $this->view->assign('data',$data);
        $this->view->display('admin/article/sort_list.html');
    }

    /**
     * 方法名称:sortEditAction
     * 说明: 添加修改分类展示
     */
    public function sortEditAction()
    {
        $uuid=$this->_request->getParam('ids');
        $uuid=is_array($uuid)?(isset($uuid[0])?$uuid[0]:''):$uuid;
        if($uuid)
        {
            if(baseModel::commCount("ben_sort",array('id'=>$uuid)))
            {
                $this->view->assign('data',baseModel::commGetDetailById("ben_sort",$uuid));
            }
            else
            {
                $this->show_message('参数传递失败！');
            }
        }
        $this->view->display('admin/article/sort_edit.html');
    }

    /**
     * 方法名称:sortSaveAction
     * 说明: 添加、修改保存分类
     */
    public function sortSaveAction()
    {
        $save_data['sort_name']=articleValidate::isMust('sort_name',$this->_request,"分类名称不能为空！");
        $save_data['sort_pinyin']=$this->_request->getParam('sort_pinyin');
        $save_data['sort_key']=$this->_request->getParam('sort_key');
        $save_data['sort_key']=$save_data['sort_key']?str_replace(array('。','.',';','；','|','-',':',"：",'!','！','?','？'),',',$save_data['sort_key']):$save_data['sort_key'];
        $save_data['sort_info']=$this->_request->getParam('sort_info');
        $save_data['sort_menu']=articleValidate::defaultStatus('sort_menu',$this->_request);
        $id=$this->_request->getParam('id');
        $save_data['updated']=date('Y-m-d H:i:s');
        $data['code']='500';
        $data['msg']='保存失败！';
        if($id)
        {
            articleValidate::isDbExist('ben_sort',array("sort_name"=>$save_data["sort_name"]),'分类名称已存在',"id != $id");
            if(baseModel::commEdit('ben_sort',$save_data,array('id'=>$id)))
            {
                $data['code']='200';
                $data['msg']='修改分类信息成功！';
                json($data,$data['code']);
            }
            else
            {
                $data['msg']='修改分类信息失败！';
                json($data,$data['code']);
            }
        }
        else
        {
            $save_data['created']=$save_data['updated'];
            if($save_data['sort_pinyin']=='')
            {
                $pinyin = new Pinyin('Overtrue\Pinyin\MemoryFileDictLoader');
                $save_data['sort_pinyin']=$pinyin->abbr($save_data['sort_name']);
            }
            if(baseModel::commAdd('ben_sort',$save_data))
            {
                $data['code']='200';
                $data['msg']='新增分类信息成功！';
                json($data,$data['code']);
            }
            else
            {
                $data['msg']='新增分类信息失败！';
                json($data,$data['code']);
            }
        }
    }

    /**
     * 方法名称:sortStatusAction
     * 说明:设置导航状态
     */
    public function sortStatusAction()
    {
        $data['code']='500';
        $data['msg']='删除记录失败！';
        $uuid=$this->_request->getParam('ids');
        if(!is_array($uuid))
        {
            $uuid=array($uuid);
        }
        if(!empty($uuid))
        {
            $succ=0;
            $error=0;
            foreach ($uuid as $k=>$v)
            {
                $basic=baseModel::commGetDetailById('ben_sort',$v);
                if($basic!==false)
                {
                    $new_status=$basic->sort_menu==1?2:1;
                    if(baseModel::commEdit('ben_sort',array('sort_menu'=>$new_status),array('id'=>$v)))
                    {
                        $succ++;
                    }
                    else
                    {
                        $error++;
                    }
                }
                else
                {
                    $error++;
                    continue;
                }
            }
            $data['code']='200';
            $data['msg']='修改完成，其中成功【'.$succ.'】条，失败【'.$error.'】条！';
        }
        else
        {
            $data['msg']='参数为空，修改失败！';
        }
        json($data,$data['code']);
    }

    /**
     * 方法名称:sortDeleteAction
     * 说明:删除分类
     */
    public function sortDeleteAction()
    {
        $uuid=$this->_request->getParam('ids');
        $data=parent::_delete("ben_sort",$uuid,array('ben_article_base'),array('ben_article_base'=>'sort_id'));
        json($data,$data['code']);
    }

}