<?php
/**
 *
 * 文件说明: 友情连接管理
 *
 * Created by PhpStorm.
 * User: qs9515
 * Date: 2019/9/8
 * Time: 20:58
 *
 * $Id$
 * $LastChangedDate$
 * $LastChangedRevision$
 * $LastChangedBy$
 */
namespace application\admin\controller;
use application\admin\models\baseModel;
use core\controller;
class otherController extends baseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 方法名称:linkListAction
     * 说明: 友情连接列表
     */
    public function linkListAction()
    {
        $search=array();
        $search['keyword']=$this->_request->getParam('keyword');
        $data=parent::_list("ben_tags",BASE_PATH.'admin/article/tagList/page/(:num)/',$search,"updated desc",array('tag_name','tag_pinyin'));
        if(!empty($data))
        {
            foreach ($data as $k=>$v)
            {
                $data[$k]['count']=baseModel::commCount('ben_tag_article',array('tid'=>$v['id']));
            }
        }
        $this->view->assign('data',$data);
        $this->view->display('admin/article/tag_list.html');
    }

    /**
     * 方法名称:templateListAction
     * 说明: 模板列表
     * @throws \SmartyException
     */
    public function templateListAction()
    {
        $search=array();
        $search['keyword']=$this->_request->getParam('keyword');
        $data=parent::_list("ben_template",BASE_PATH.'admin/other/templateList/page/(:num)/',$search,"updated desc",array('template_name'));
        $this->view->assign('data',$data);
        $this->view->display('admin/other/template_list.html');
    }

    /**
     * 方法名称:templateEditAction
     * 说明: 模板信息新增、修改展现
     */
    public function templateEditAction()
    {

    }
}