<?php
/**
 *
 * 文件说明: 系统配置管理
 *
 * Created by PhpStorm.
 * User: qs9515
 * Date: 2019/8/18
 * Time: 10:58
 *
 * $Id$
 * $LastChangedDate$
 * $LastChangedRevision$
 * $LastChangedBy$
 */
namespace application\admin\controller;
use application\admin\controller\baseController;
use application\admin\models\systemModel;
use application\admin\validate\confValidate;
use core\conf;

class systemController extends baseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 方法名称:confAction
     * 说明: 展示系统配置信息
     * @throws \SmartyException
     */
    public function confAction()
    {
        $conf=systemModel::getConfDetail();
        $this->view->assign('data',$conf);
        $this->view->display("admin/system/conf_edit.html");
    }

    /**
     * 方法名称:confSaveAction
     * 说明: 系统配置信息保存
     */
    public function confSaveAction()
    {
        $save_data['system_name']=confValidate::isMust('system_name',$this->_request,"网站名称不能为空！");
        $save_data['system_key']=$this->_request->getParam('system_key');
        $save_data['system_info']=$this->_request->getParam('system_info');
        $save_data['status']=confValidate::defaultStatus('status',$this->_request);
        $save_data['template_dir']=$this->_request->getParam('template_dir');
        $save_data['system_company']=$this->_request->getParam('system_company');
        $save_data['footer_script']=$this->_request->getParam('footer_script');
        $save_data['icp']=$this->_request->getParam('icp');
        $save_data['copyright_name']='144d.com';
        $save_data['copyright_year']='2019';
        $save_data['created']=$save_data['updated']=date('Y-m-d H:i:s');
        $data['code']='500';
        $data['msg']='保存失败！';
        if (systemModel::confSave($save_data))
        {
            $data['code']='200';
            $data['msg']='保存成功！';
            json($data,$data['code']);
        }
        else
        {
            json($data,$data['code']);
        }
    }

    /**
     * 方法名称:loginLogAction
     * 说明: 登陆日志列表
     */
    public function loginLogAction()
    {
        $search=array();
        $search['keyword']=$this->_request->getParam('keyword');
        $data=parent::_list("ben_login_logs",BASE_PATH.'admin/system/loginLog/page/(:num)/',$search,"updated desc",array('name','source','ua','res'));
        $this->view->assign('data',$data);
        $this->view->display('admin/system/loginLog_list.html');
    }

    /**
     * 方法名称:loginLogDeleteAction
     * 说明: 登陆日志删除
     */
    public function loginLogDeleteAction()
    {
        $uuid=$this->_request->getParam('ids');
        $data=parent::_delete("ben_login_logs",$uuid);
        json($data,$data['code']);
    }

    /**
     * 方法名称:loginLogDetailAction
     * 说明: 查看日志详细
     * @throws \SmartyException
     */
    public function loginLogDetailAction()
    {
        $uuid=$this->_request->getParam('ids');
        $uuid=is_array($uuid)?(isset($uuid[0])?$uuid[0]:''):$uuid;
        if($uuid)
        {
            if(systemModel::commCount("ben_login_logs",array("id"=>$uuid)))
            {
                $conf=systemModel::commGetDetailById("ben_login_logs",$uuid);
                $this->view->assign('data',$conf);
                $this->view->display('admin/system/loginLog_detail.html');
            }
            else
            {
                $this->show_message("记录不存在！");
            }
        }
        else
        {
            $this->show_message("参数错误！");
        }
    }

    /**
     * 方法名称:eventLogAction
     * 说明:前台访问日志列表
     */
    public function eventLogAction()
    {
        $search=array();
        $search['keyword']=$this->_request->getParam('keyword');
        $data=parent::_list("ben_views_logs",BASE_PATH.'admin/system/eventLog/page/(:num)/',$search,"updated desc",array('source','ua'));
        $this->view->assign('data',$data);
        $this->view->display('admin/system/eventLog_list.html');
    }

    /**
     * 方法名称:eventLogDeleteAction
     * 说明: 删除访问日志
     */
    public function eventLogDeleteAction()
    {
        $uuid=$this->_request->getParam('ids');
        $data=parent::_delete("ben_views_logs",$uuid);
        json($data,$data['code']);
    }

    /**
     * 方法名称:eventLogDetailAction
     * 说明: 查看日志详细
     * @throws \SmartyException
     */
    public function eventLogDetailAction()
    {
        $uuid=$this->_request->getParam('ids');
        $uuid=is_array($uuid)?(isset($uuid[0])?$uuid[0]:''):$uuid;
        if($uuid)
        {
            if(systemModel::commCount("ben_views_logs",array("id"=>$uuid)))
            {
                $conf=systemModel::commGetDetailById("ben_views_logs",$uuid);
                $this->view->assign('data',$conf);
                $this->view->display('admin/system/eventLog_detail.html');
            }
            else
            {
                $this->show_message("记录不存在！");
            }
        }
        else
        {
            $this->show_message("参数错误！");
        }
    }
}